import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from 'next/image'
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web1.png"
import web3 from "../public/web3.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import { useState } from 'react'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false); 
  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>Henry Aléssandro Lürssen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-beige px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>Itsami Alessandro</h1>

            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode (!darkMode)} className="cursor-pointer text-2xl"/></li>
              <li><a className='bg-gradient-to-r from-orange-500 to-yellow-500 text-white px-4 py-2 rounded-md ml-8'href="#">Resume</a></li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='py-2 text-5xl font-medium md:text-6xl text-transparent bg-clip-text bg-gradient-to-r from-orange-500 to-yellow-400'>Henry Alessando Lurssen</h2>
            <h3 className='text-2xl py-3 md:text-3xl dark:text-white'>Developer, Designer, Engineer.</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white md:text-xl max-w-xl mx-auto'>Welcome possible future employer! My name is Henry A. Lurssen. I'm an ex (undergrad) medical student and now junior software engineer based in Boston, MA. (actually greater Boston. But just saying Boston makes it easier for everyone) </p>
          </div>

          <div className='text-5xl flex justify-center gap-16 dark:bg-gray-700 '>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-orange-400 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96'>
            <Image src={deved} layout="fill" objectFit='cover' alt=''/>
          </div>

        </section>

        <section>
          <div className='text-center p-10'>
            <h3 className='text-3xl py-1 flex justify-center dark:text-white'>Brief Intro :</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Since I began my journey as a developer, I've always given my attention to things that could help me <span className='text-orange-400'>elevate</span> my skill. As of today, I have not yet worked with any tech companies. That is not to say that I am useless but that Im sort of like a clean <span className='text-orange-400'>canvas</span> to work with, one that wont bring any bad habits to whatever team Im placed in haha. </p>
          </div>

          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-black'>Designs</h3>
              <p className='py-2 dark:text-black'>Creations made by using my brain meats and beautiful core design theory (Taught by the spectacular Professor Google and the Coding Dojo Facility) Always getting ispiration from websites like Nike, Apple, and TikTok.</p>
              <h4 className='py-4 text-orange-400 dark:text-black'>Tools I Use</h4>
              <p className='text-gray-800 py-1 dark:text-black'>Figma</p>
              <p className='text-gray-800 py-1 dark:text-black'>Illustrator</p>
              <p className='text-gray-800 py-1 dark:text-black'>Three.js</p>
              <p className='text-gray-800 py-1 dark:text-black'>Tailwind CSS</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-black'>Code</h3>
              <p className='py-2 dark:text-black'>From smaller YouTube instructors to ex-google ex facebook tech lead lectures, my code is based on the most proffecient and easy to read in what is coding syntax and grammar. </p>
              <h4 className='py-4 text-orange-400 dark:text-black'>Tools I Use</h4>
              <p className='text-gray-800 py-1 dark:text-black'>Atom</p>
              <p className='text-gray-800 py-1 dark:text-black'>GitHub</p>
              <p className='text-gray-800 py-1 dark:text-black'>IntelliJ IDEA</p>
              <p className='text-gray-800 py-1 dark:text-black'>Visual Code Studio</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-black'>Consulting</h3>
              <p className='py-2 dark:text-black'>Turning ideas into real life <span className='text-orange-600'>Products</span> is my calling. In school, most of what I did to help MYSELF was help OTHERS. Anything from HTML/CSS to using tools like Figma and Tailwind or algorithmic problems.</p>
              <h4 className='py-4 text-orange-400 dark:text-black'>Languages I Use</h4>
              <p className='text-gray-800 py-1 dark:text-black'>C#</p>
              <p className='text-gray-800 py-1 dark:text-black'>Java</p>
              <p className='text-gray-800 py-1 dark:text-black'>Python3</p>
              <p className='text-gray-800 py-1 dark:text-black'>JavaScipt</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 flex justify-center text-orange-400' >Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 text-center dark:text-white'>These images are templates of pages I am working on creating(Nike one is for last). I have one other finished (but not deployed) site where people can post their pets and display a photo of them along with basic information. The site also has a working login and registration system using MySQL. The Pets site is not the prettiest, CSS wasnt used very much and I mainly stuck to Bootstrap.</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg: flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>

          <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-black'>Contact Me</h3>
              <p className='py-2 dark:text-black'>I am <span className='text-orange-500'>ALWAYS</span> eager to hear from anyone! If you'd like to contact me, look towards the following please! <span className='text-orange-500'>(Links below do work)</span>.</p>
              <h4 className='py-2 text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-orange-500 to-yellow-400'>Hey! Look Here:</h4>
              <p className='py-2 text-xl font-medium text-transparent bg-clip-text bg-gradient-to-r from-orange-500 to-yellow-400'>Email: Henrylurssen@gmail.com</p>
              <p><a href="https://www.linkedin.com/in/henry-lurssen-47127822a/" target="_blank" className='py-2 text-xl font-medium text-transparent bg-clip-text bg-gradient-to-r from-orange-500 to-yellow-400'>LinkedIn</a></p>
              <p><a href="https://github.com/HLurssen" target="_blank" className='py-2 text-xl font-medium text-transparent bg-clip-text bg-gradient-to-r from-orange-500 to-yellow-400'>GitHub</a></p>
            </div>

        </section>
      </main>
    </div>
  )
}
